config/routes.rb
Rails.application.routes.draw do
	get 'employees/custom'
get'/employees/relocate_request' , to: 'employees#relocate_request' 
  resources :employees
  resources :cities
  resources :managers

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :employees
	validates :name , uniqueness:true , presence:true
	
end

app/models/employee.rb
class Employee < ApplicationRecord
	belongs_to :city
	has_many :subordinates, class_name: "Employee",
                          foreign_key: "manager_id"
 
  belongs_to :manager, class_name: "Employee", optional: :true
  validates :name , presence:true , uniqueness:true
  validates :willingtorelocate , absence:true , on: :create
  has_attached_file :photo , :styles => { :small => "150x150>"}
  validates_attachment_presence :photo
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png' ,'image/gif']
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name , :id)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
 

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all

  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  
  end

  # GET /employees/new
  def new
    @employee = Employee.new

  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
     @employee = Employee.find(params[:id])
    @employee.update(employee_params)
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
       @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :city_id,:manager_id,:willingtorelocate ,:photo)
    end
    def relocate_request
    end
     def custom
        @ajax = City.limit(10)
      respond_to do |format|
        format.js
        format.html
      end
    end
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  before_action :set_manager, only: [:show, :edit, :update, :destroy]

  # GET /managers
  # GET /managers.json
  def index
    @managers = Employee.where('id IN (SELECT manager_id FROM employees)')
    @posts = Employee.paginate(:page => params[:page])
    

  end

  # GET /managers/1
  # GET /managers/1.json
  def show

  end

  # GET /managers/new
  def new
    @manager = Manager.new
  end

  # GET /managers/1/edit
  def edit
  end

  # POST /managers
  # POST /managers.json
  def create
    @manager = Manager.new(manager_params)

    respond_to do |format|
      if @manager.save
        format.html { redirect_to @manager, notice: 'Manager was successfully created.' }
        format.json { render :show, status: :created, location: @manager }
      else
        format.html { render :new }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /managers/1
  # PATCH/PUT /managers/1.json
  def update
    respond_to do |format|
      if @manager.update(manager_params)
        format.html { redirect_to @manager, notice: 'Manager was successfully updated.' }
        format.json { render :show, status: :ok, location: @manager }
      else
        format.html { render :edit }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /managers/1
  # DELETE /managers/1.json
  def destroy
    @manager.destroy
    respond_to do |format|
      format.html { redirect_to managers_url, notice: 'Manager was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manager
      @manager = Manager.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manager_params
      params.fetch(:manager, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/views/cities/_form.html.erb
<%= form_for(city) do |f| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%=f.label :name%>
  <%=f.text_field :name%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cities</h1>
<p>COUNT =<%= @cities.count %></p>
<ol>
<table>
  <thead>
    <tr>
    <th>Sr.no</th>
    <th>Name</th>
    <th>Total employees</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><li></li></td>
        <td><%= link_to city.name ,city %></td>
        <td><%= city.employees.count %></td>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</ol>

<br>

<%= link_to 'New City', new_city_path %>

app/views/cities/new.html.erb
<h1>New City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>
<p>
	<strong>Name</strong>
	<%= @city.name %>
</p>
<p>
	<strong>Total Employees</strong>
	<%= @city.employees.count %>
</p>
<ol>
<table>
  <thead>
    <tr>
    <th>Sr.no</th>
    <th>Name</th>
    <th>Manager's name</th>
    <th>Manager's city</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <% @city.employees.each do |employee| %>
      <tr>
        <td><li></li></td>
        <td><%= employee.name %></td>
        <td><%= employee.manager.present? ? employee.manager.name : ""%></td>
        <td><%= employee.manager.city.present? ? employee.manager.city.name : ""%></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</ol>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

app/views/employees/_form.html.erb
<script>
  $(document).ready(function() {
    $(#).change(function(){
      $.ajax({
        
        data: {
           c_id: $("#city_id option:selected").text(),
        },
        datatype: "script"
      });
    });
  });
</script>
<%= form_for @employee ,:html => { :multipart => true} do |f| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
  <%=f.label :name%>
  <%=f.text_field :name%>
  </div>

  <div class="field">
  <%=f.label :city_id%>
  <%=f.collection_select :city_id,City.all, :id, :name %>
  </div>

  <!-- <div id="message">
     <p>ERROR</p>    
  </div> -->
  
  <div class="field">
  <%=f.label "willing to relocate"%>
  <%= f.check_box :willingtorelocate%> <br/>
  </div>

  <p>
    <%=f.file_field :photo %>
    
  </p>

  <div class="actions">
    <%= f.submit  %>
  </div>
<% end %>

app/views/employees/custom.js.erb
$('#message').html("<%= j (render 'show_custom') %>")

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> 
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>
<ol>
<table>
  <thead>
    <tr>
    <th>Sr.no</th>
    <th>Profile photo</th>
    <th>Name</th>
    <th>City</th>
    <th>Manager</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
      <td><li></li></td>
      <td><%= link_to (image_tag employee.photo.url(:small)) , employee %></td>
      <td><%= employee.name %></td>
      <td><%= employee.city_id %></td>
      <td><%= employee.manager.present? ?employee.manager.name : "" %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</ol>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/relocate_request.html.erb
<h1>Employees</h1>
<p>Relocation Count= <%=Employee.where(willingtorelocate: true).count %></p>
 <ol>
  <table>
  <thead>
    <tr>
    <th>Sr.no</th>
    <th>Name</th>
    <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   <%Employee.where(willingtorelocate: true).each do |employee|%>
      <tr>
      <td><li></li></td>
      <td><%= link_to employee.name ,edit_employee_path(employee)%></td>
      <td><%= employee.city.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</ol>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

  <p>
  <% if @employee.photo.exists? %>
      <%= image_tag @employee.photo.url(:small) %><br/>
  <% end %>
</p>

<p>
<strong>ID</strong>
<%= @employee.manager_id %>
</p>

<p>
<strong>Name</strong>
<%= @employee.name %>
</p>

<p>
<strong>City</strong>
<%= @employee.city.name %>
</p>

<p>
<strong>Subordinates</strong>
<%= @employee.subordinates.count %>
</p>
 <ol>
 	<table>
  <thead>
    <tr>
    <th>Sr.no</th>
    <th>Name</th>
    <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @employee.subordinates.each do |sub| %>
      <tr>
      <td><li></li></td>
       <td><%= sub.name %></td>
        <td><%= sub.city.name %></td>
         </tr>       
    <% end %>
  </tbody>
  
</table>
</ol>


<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', managers_path %>

app/views/employees/show_custom.html.erb
error

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assignment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/managers/_form.html.erb
<%= form_for(manager) do |f| %>
  <% if manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(manager.errors.count, "error") %> prohibited this manager from being saved:</h2>

      <ul>
      <% manager.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/managers/edit.html.erb
<h1>Editing Manager</h1>

<%= render 'form', manager: @manager %>

<%= link_to 'Show', @manager %> |
<%= link_to 'Back', managers_path %>

app/views/managers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Managers</h1>
<ol>
<table>
  <thead>
    <tr>
    <th>Sr.no</th>
    <th>Name</th>
    <th>City</th>
    <th>Sub</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @managers.each do |manager| %>
      <tr>
      <td><li></li></td>
       <td><%= link_to manager.name, manager %></td>
        <!-- <td><#%= manager.city.name %></td> -->
        <td><%=manager.subordinates.count %></td>
        <td><%= link_to 'Show', manager %></td>
        <td><%= link_to 'Edit', edit_manager_path(manager) %></td>
        <td><%= link_to 'Destroy', manager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
         </tr>       
    <% end %>
  </tbody>
  
</table>
</ol>


<br>

<%= link_to 'New Manager', new_manager_path %>
<%= will_paginate @posts %>

app/views/managers/new.html.erb
<h1>New Manager</h1>

<%= render 'form', manager: @manager %>

<%= link_to 'Back', managers_path %>

app/views/managers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_manager_path(@manager) %> |
<%= link_to 'Back', managers_path %>